version: '3.8'

services:
  frontend:
    build: frontend/.
    ports:
      - "80:80"
    environment:
      BACKEND_URL: http://backend:8080/api/
    depends_on:
      - backend

  backend:
    build: 
      context: .
      args:
        ARTIFACT_ID: ${APP_ARTIFACT_ID}
        VERSION: ${APP_VERSION}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/headless-cms
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: headless-cms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
