services:
  frontend:
    build: frontend/.
    ports:
      - "8094:8094"
    environment:
      BACKEND_URL: http://backend:8092/api/
    depends_on:
      - backend

  backend:
    build: 
      context: .
      args:
        ARTIFACT_ID: ${APP_ARTIFACT_ID}
        VERSION: ${APP_VERSION}
    ports:
      - "8092:8092"
    environment:
      SPRING_HOST_URL: ${HOST_URL} # replace it with your domain name
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg.alphasow.dev:5432/headless-cms
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
