spring:
  application:
    name: Headless CMS
  config:
    activate:
      on-profile: prod
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema.sql
app:    
 HOST_URL: ${SPRING_HOST_URL}
      
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

springdoc:
  swagger-ui:
    path: /
    
server:
  error:
    include-stacktrace: never
    include-message: on_param
    include-binding-errors: never
    include-exception: false