spring:
  application:
    name: Headless CMS
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: jdbc:postgresql://localhost:5432/headless-cms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema.sql
      
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

springdoc:
  swagger-ui:
    path: /docs
    
server:
  error:
    include-stacktrace: never
    include-message: on_param
    include-binding-errors: never
    include-exception: false